/*
    BEGIN
        DBMS_OUTPUT.put_line(f_get_ddl_query('INTERN','AIRLINES'));
    END;
*/

CREATE TABLE AIRLINES (
	AIRLINE_ID	NUMBER(22),
	AIRLINE_NAME	VARCHAR2(150)
	);

ALTER TABLE AIRLINES
ADD CONSTRAINT PK_AIRLINES UNIQUE(AIRLINE_ID);